In [3]:
import pandas as pd
import numpy as np

In [4]:
df= pd.DataFrame({
    "A":[1, -2, 3, -4, 5],
    "B":[6, -7, 8, -9, 10],
    "C":[11, -12, 13, -14, 15]
})

In [5]:
df

   A   B   C
0  1   6  11
1 -2  -7 -12
2  3   8  13
3 -4  -9 -14
4  5  10  15

In [6]:
df.apply(abs)

   A   B   C
0  1   6  11
1  2   7  12
2  3   8  13
3  4   9  14
4  5  10  15

In [7]:
abs(-1.111)

1.111

In [8]:
abs(1.111)

1.111

In [9]:
type(df['A'])

pandas.core.series.Series

In [10]:
df['A']

0    1
1   -2
2    3
3   -4
4    5
Name: A, dtype: int64

In [11]:
df['A'].apply(abs)

0    1
1    2
2    3
3    4
4    5
Name: A, dtype: int64

In [12]:
df[['A','C']].apply(abs)

   A   C
0  1  11
1  2  12
2  3  13
3  4  14
4  5  15

In [13]:
df['A'].apply(np.negative)   # змінює знак кожного числа у стовпці 'A' на протилежний

0   -1
1    2
2   -3
3    4
4   -5
Name: A, dtype: int64

In [14]:
np.negative(1)

np.int64(-1)

In [15]:
np.negative(-101)

np.int64(101)

In [16]:
def minus_five(value):
    return value - 5

In [17]:
minus_five(15)

10

In [18]:
df['A'].apply(minus_five)

0   -4
1   -7
2   -2
3   -9
4    0
Name: A, dtype: int64

In [19]:
minus_five(df['A'])

0   -4
1   -7
2   -2
3   -9
4    0
Name: A, dtype: int64

In [20]:
df['A'].tolist()

[1, -2, 3, -4, 5]

In [21]:
def plus_three(value):
    return value + 3

In [22]:
df['A'].apply(minus_five).apply(plus_three)

0   -1
1   -4
2    1
3   -6
4    3
Name: A, dtype: int64

In [23]:
# Послідовне застосування функцій до стовпця 'A':віднімання 5, додавання 3, зміна знака та фінальне додавання 3
df['A'].apply(minus_five).apply(plus_three).apply(np.negative).apply(plus_three)

0    4
1    7
2    2
3    9
4    0
Name: A, dtype: int64

In [24]:
def add_number(value, number_to_add):
    return value + number_to_add

In [27]:
df['A'].apply(add_number, args =(10,))

0    11
1     8
2    13
3     6
4    15
Name: A, dtype: int64

In [28]:
df['A'].apply(add_number, number_to_add = 5)

0     6
1     3
2     8
3     1
4    10
Name: A, dtype: int64

In [29]:
def add_number(value, number_to_add, args2):
  return value + number_to_add - args2

In [31]:
df['A'].apply(add_number, number_to_add=10, args2 = 100)

0   -89
1   -92
2   -87
3   -94
4   -85
Name: A, dtype: int64

### Застосування функції, яка визначає тип даних

In [33]:
df = pd.DataFrame({
    "A": [1, "2", 3.0, "4", True],
    "B": [5, "6", 7.0, "8", False]
})

In [36]:
df

      A      B
0     1      5
1     2      6
2   3.0    7.0
3     4      8
4  True  False

In [34]:
def dtype(x):
    if isinstance(x, int):    # Якщо значення x є цілим числом (наприклад, 5 або -10)
        return "int"          # тоді повертаємо текстовий рядок "int"
    elif isinstance(x, float):    # Інакше, якщо x є числом з крапкою (наприклад, 3.14)
        return "float"            # повертаємо рядок "float"
    elif isinstance(x, str):      # Інакше, якщо x є текстовим рядком (наприклад, "Привіт")
        return "str"              # повертаємо рядок "str"
    elif isinstance(x, bool):     # Інакше, якщо x є логічним значенням (True або False)
        return "bool"             # повертаємо рядок "bool"
    else:                         # Якщо тип не збігається з жодним із перелічених вище
        return "unknown"          # повертаємо рядок "unknown" (невідомо)

In [35]:
df['A'].apply(dtype)   # Застосувати функцію dtype до кожного елемента у стовпці 'A'

0      int
1      str
2    float
3      str
4      int
Name: A, dtype: object

### Застосування функції, яка повертає текст у числа

In [37]:
df = pd.DataFrame({
    "A":["1", "2", "3", "4", "5"],
    "B":["6", "7", "8", "9", "10"]
})

In [38]:
def to_number(x):
    return int(x)

In [39]:
df['B'].apply(to_number)

0     6
1     7
2     8
3     9
4    10
Name: B, dtype: int64

### Застосування функції, яка обчислює відсоток від загальної суми

In [41]:
df = pd.DataFrame({
    "A":[10, 20, 30, 40, 50],
    "B":[60, 70, 80, 90, 100],
    "C":[70, 10, 20, 40, 90]
})

In [51]:
def percent(x, total):  # Оголошуємо функцію з назвою percent, яка приймає два аргументи: саме число (x) та загальну суму (total)
    return(x/total) * 100    # Ділимо число на загальну суму (отримуємо частку) та множимо на 100, щоб перевести у відсотки

In [45]:
df['A'].sum()*100

np.int64(15000)

In [47]:
df['A'].apply(percent, total=df['A'].sum())

0     6.666667
1    13.333333
2    20.000000
3    26.666667
4    33.333333
Name: A, dtype: float64

In [50]:
 # перевіряємо чи правильно порахувало суму, має вивести 100
df['A'].apply(percent, total= df['A'].sum()).sum()

np.float64(100.0)

In [53]:
df.apply(percent, axis=1, total = df.sum())  # застосування до всіх колонок

           A     B          C
0   6.666667  15.0  30.434783
1  13.333333  17.5   4.347826
2  20.000000  20.0   8.695652
3  26.666667  22.5  17.391304
4  33.333333  25.0  39.130435

In [56]:
df.sum()  #Сума всіх колонок

A    150
B    400
C    230
dtype: int64

In [57]:
df.apply(percent, axis=1, total = df.sum()).sum()  # Перевірити себе. Щоб по всіх колонках було 100

A    100.0
B    100.0
C    100.0
dtype: float64

### Застосування суми до всіх рядів датафрейму

In [58]:
df

    A    B   C
0  10   60  70
1  20   70  10
2  30   80  20
3  40   90  40
4  50  100  90

In [59]:
df.apply(sum, axis = 1)

0    140
1    100
2    130
3    170
4    240
dtype: int64