In [4]:
import pandas as pd
import numpy as np

In [5]:
df= pd.read_csv('health_insurance_cross_sell_prediction.csv')

In [6]:
# Подивимося тип дата фрейму
type(df)

pandas.core.frame.DataFrame

In [7]:
# Подивимося розмір дата фрейму
df_shape=df.shape
df_shape

(381109, 12)

Тобто розмір файлу: 
381109 рядочків, 12 колонок

In [8]:
# дізнатися кількість рядочків
df.shape[0]

381109

In [9]:
# дізнатися кількість колонок
df.shape[1]

12

In [10]:
len(df)

381109

In [11]:
#Подивитися розмір колонок(в бітах)
df.memory_usage()

Index                       132
id                      3048872
Gender                  3048872
Age                     3048872
Driving_License         3048872
Region_Code             3048872
Previously_Insured      3048872
Vehicle_Age             3048872
Vehicle_Damage          3048872
Annual_Premium          3048872
Policy_Sales_Channel    3048872
Vintage                 3048872
Response                3048872
dtype: int64

In [12]:
# Просумувати розмір колонок
df.memory_usage().sum()

np.int64(36586596)

In [13]:
# Перевести з бітів в мегабайти
total_bytes = df.memory_usage().sum()
total_megabytes = total_bytes/(1024*1024)
total_megabytes

np.float64(34.89169692993164)

In [14]:
# Зчитати частину даних(100 рядків)
pd.read_csv('health_insurance_cross_sell_prediction.csv', nrows = 100)

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,1,Male,44,1,28.0,0,> 2 Years,Yes,40454.0,26.0,217,1
1,2,Male,76,1,3.0,0,1-2 Year,No,33536.0,26.0,183,0
2,3,Male,47,1,28.0,0,> 2 Years,Yes,38294.0,26.0,27,1
3,4,Male,21,1,11.0,1,< 1 Year,No,28619.0,152.0,203,0
4,5,Female,29,1,41.0,1,< 1 Year,No,27496.0,152.0,39,0
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Female,23,1,30.0,0,< 1 Year,No,26689.0,152.0,254,0
96,97,Male,50,1,28.0,0,1-2 Year,Yes,46995.0,52.0,291,0
97,98,Female,62,1,28.0,0,> 2 Years,Yes,41892.0,155.0,114,0
98,99,Female,21,1,2.0,0,< 1 Year,Yes,34274.0,152.0,79,0
99,100,Female,24,1,7.0,1,< 1 Year,Yes,2630.0,160.0,68,0

In [15]:
# перші 10 записів
df.head(10)

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,1,Male,44,1,28.0,0,> 2 Years,Yes,40454.0,26.0,217,1
1,2,Male,76,1,3.0,0,1-2 Year,No,33536.0,26.0,183,0
2,3,Male,47,1,28.0,0,> 2 Years,Yes,38294.0,26.0,27,1
3,4,Male,21,1,11.0,1,< 1 Year,No,28619.0,152.0,203,0
4,5,Female,29,1,41.0,1,< 1 Year,No,27496.0,152.0,39,0
5,6,Female,24,1,33.0,0,< 1 Year,Yes,2630.0,160.0,176,0
6,7,Male,23,1,11.0,0,< 1 Year,Yes,23367.0,152.0,249,0
7,8,Female,56,1,28.0,0,1-2 Year,Yes,32031.0,26.0,72,1
8,9,Female,24,1,3.0,1,< 1 Year,No,27619.0,152.0,28,0
9,10,Female,32,1,6.0,1,< 1 Year,No,28771.0,152.0,80,0

In [16]:
# Останні 5 записів
df.tail(5)

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
381104,381105,Male,74,1,26.0,1,1-2 Year,No,30170.0,26.0,88,0
381105,381106,Male,30,1,37.0,1,< 1 Year,No,40016.0,152.0,131,0
381106,381107,Male,21,1,30.0,1,< 1 Year,No,35118.0,160.0,161,0
381107,381108,Female,68,1,14.0,0,> 2 Years,Yes,44617.0,124.0,74,0
381108,381109,Male,46,1,29.0,0,1-2 Year,No,41777.0,26.0,237,0

In [17]:
# Покажи від 100-го до 110 рядочка з кроком 2
df[100:110:2]

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
100,101,Male,52,1,28.0,1,1-2 Year,No,36033.0,26.0,92,0
102,103,Female,20,1,30.0,0,< 1 Year,Yes,33227.0,160.0,78,0
104,105,Male,29,1,41.0,1,< 1 Year,Yes,43046.0,163.0,222,0
106,107,Female,23,1,41.0,1,< 1 Year,No,36674.0,152.0,158,0
108,109,Male,72,1,46.0,1,1-2 Year,Yes,28698.0,30.0,216,0

In [18]:
df.loc[200]

id                           201
Gender                      Male
Age                           55
Driving_License                1
Region_Code                 28.0
Previously_Insured             0
Vehicle_Age             1-2 Year
Vehicle_Damage               Yes
Annual_Premium           49470.0
Policy_Sales_Channel       124.0
Vintage                      203
Response                       0
Name: 200, dtype: object

In [19]:
df[200] # помилка. в дужках очікується назва колонки

KeyError: 200

In [21]:
df[:5] # виведе до 5 рядка включно

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,1,Male,44,1,28.0,0,> 2 Years,Yes,40454.0,26.0,217,1
1,2,Male,76,1,3.0,0,1-2 Year,No,33536.0,26.0,183,0
2,3,Male,47,1,28.0,0,> 2 Years,Yes,38294.0,26.0,27,1
3,4,Male,21,1,11.0,1,< 1 Year,No,28619.0,152.0,203,0
4,5,Female,29,1,41.0,1,< 1 Year,No,27496.0,152.0,39,0

In [22]:
df[5:] #виведе все починаючи з 5 рядка

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
5,6,Female,24,1,33.0,0,< 1 Year,Yes,2630.0,160.0,176,0
6,7,Male,23,1,11.0,0,< 1 Year,Yes,23367.0,152.0,249,0
7,8,Female,56,1,28.0,0,1-2 Year,Yes,32031.0,26.0,72,1
8,9,Female,24,1,3.0,1,< 1 Year,No,27619.0,152.0,28,0
9,10,Female,32,1,6.0,1,< 1 Year,No,28771.0,152.0,80,0
...,...,...,...,...,...,...,...,...,...,...,...,...
381104,381105,Male,74,1,26.0,1,1-2 Year,No,30170.0,26.0,88,0
381105,381106,Male,30,1,37.0,1,< 1 Year,No,40016.0,152.0,131,0
381106,381107,Male,21,1,30.0,1,< 1 Year,No,35118.0,160.0,161,0
381107,381108,Female,68,1,14.0,0,> 2 Years,Yes,44617.0,124.0,74,0
381108,381109,Male,46,1,29.0,0,1-2 Year,No,41777.0,26.0,237,0

In [23]:
df.loc[100]

id                           101
Gender                      Male
Age                           52
Driving_License                1
Region_Code                 28.0
Previously_Insured             1
Vehicle_Age             1-2 Year
Vehicle_Damage                No
Annual_Premium           36033.0
Policy_Sales_Channel        26.0
Vintage                       92
Response                       0
Name: 100, dtype: object

In [24]:
type(df.loc[100])

pandas.core.series.Series

In [25]:
df.loc[100:101]

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
100,101,Male,52,1,28.0,1,1-2 Year,No,36033.0,26.0,92,0
101,102,Male,24,1,3.0,1,< 1 Year,No,28139.0,152.0,52,0

In [26]:
# Зробити з Series формат Data Frame
pd.DataFrame(df.loc[300])

                           300
id                         301
Gender                    Male
Age                         21
Driving_License              1
Region_Code               29.0
Previously_Insured           1
Vehicle_Age           < 1 Year
Vehicle_Damage              No
Annual_Premium         43798.0
Policy_Sales_Channel     152.0
Vintage                    258
Response                     0

In [27]:
pd.DataFrame(df.loc[300]).T   # хочу розвернути(транспонувати) за допомогою " .Т "

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
300,301,Male,21,1,29.0,1,< 1 Year,No,43798.0,152.0,258,0

In [28]:
df[100:110:2].iloc[0]

id                           101
Gender                      Male
Age                           52
Driving_License                1
Region_Code                 28.0
Previously_Insured             1
Vehicle_Age             1-2 Year
Vehicle_Damage                No
Annual_Premium           36033.0
Policy_Sales_Channel        26.0
Vintage                       92
Response                       0
Name: 100, dtype: object

In [29]:
# буде помилка
df[100:110:2].iloc[100]

IndexError: single positional indexer is out-of-bounds

In [30]:
df[499:550:3].iloc[0]

id                           500
Gender                      Male
Age                           20
Driving_License                1
Region_Code                 36.0
Previously_Insured             1
Vehicle_Age             < 1 Year
Vehicle_Damage                No
Annual_Premium           27397.0
Policy_Sales_Channel       152.0
Vintage                       13
Response                       0
Name: 499, dtype: object

In [31]:
df.dtypes

id                        int64
Gender                   object
Age                       int64
Driving_License           int64
Region_Code             float64
Previously_Insured        int64
Vehicle_Age              object
Vehicle_Damage           object
Annual_Premium          float64
Policy_Sales_Channel    float64
Vintage                   int64
Response                  int64
dtype: object

In [32]:
df.columns

Index(['id', 'Gender', 'Age', 'Driving_License', 'Region_Code',
       'Previously_Insured', 'Vehicle_Age', 'Vehicle_Damage', 'Annual_Premium',
       'Policy_Sales_Channel', 'Vintage', 'Response'],
      dtype='object')

In [33]:
df.describe()

,id,Age,Driving_License,Region_Code,Previously_Insured,Annual_Premium,Policy_Sales_Channel,Vintage,Response
count,381109.000000,381109.000000,381109.000000,381109.000000,381109.000000,381109.000000,381109.000000,381109.000000,381109.000000
mean,190555.000000,38.822584,0.997869,26.388807,0.458210,30564.389581,112.034295,154.347397,0.122563
std,110016.836208,15.511611,0.046110,13.229888,0.498251,17213.155057,54.203995,83.671304,0.327936
min,1.000000,20.000000,0.000000,0.000000,0.000000,2630.000000,1.000000,10.000000,0.000000
25%,95278.000000,25.000000,1.000000,15.000000,0.000000,24405.000000,29.000000,82.000000,0.000000
50%,190555.000000,36.000000,1.000000,28.000000,0.000000,31669.000000,133.000000,154.000000,0.000000
75%,285832.000000,49.000000,1.000000,35.000000,1.000000,39400.000000,152.000000,227.000000,0.000000
max,381109.000000,85.000000,1.000000,52.000000,1.000000,540165.000000,163.000000,299.000000,1.000000

In [34]:
with pd.option_context("display.precision", 2):
    display(df.describe())

,id,Age,Driving_License,Region_Code,Previously_Insured,Annual_Premium,Policy_Sales_Channel,Vintage,Response
count,381109.00,381109.00,381109.00,381109.00,381109.00,381109.00,381109.00,381109.00,381109.00
mean,190555.00,38.82,1.00,26.39,0.46,30564.39,112.03,154.35,0.12
std,110016.84,15.51,0.05,13.23,0.50,17213.16,54.20,83.67,0.33
min,1.00,20.00,0.00,0.00,0.00,2630.00,1.00,10.00,0.00
25%,95278.00,25.00,1.00,15.00,0.00,24405.00,29.00,82.00,0.00
50%,190555.00,36.00,1.00,28.00,0.00,31669.00,133.00,154.00,0.00
75%,285832.00,49.00,1.00,35.00,1.00,39400.00,152.00,227.00,0.00
max,381109.00,85.00,1.00,52.00,1.00,540165.00,163.00,299.00,1.00

In [35]:
with pd.option_context("display.precision", 2):
    display(df.describe(percentiles=[0.01, 0.1, 0.2, 0.5, 0.7, 0.9, 0.99]))

,id,Age,Driving_License,Region_Code,Previously_Insured,Annual_Premium,Policy_Sales_Channel,Vintage,Response
count,381109.00,381109.00,381109.00,381109.00,381109.00,381109.00,381109.00,381109.00,381109.00
mean,190555.00,38.82,1.00,26.39,0.46,30564.39,112.03,154.35,0.12
std,110016.84,15.51,0.05,13.23,0.50,17213.16,54.20,83.67,0.33
min,1.00,20.00,0.00,0.00,0.00,2630.00,1.00,10.00,0.00
1%,3812.08,20.00,1.00,2.00,0.00,2630.00,8.00,12.00,0.00
10%,38111.80,22.00,1.00,8.00,0.00,2630.00,26.00,38.00,0.00
20%,76222.60,24.00,1.00,11.00,0.00,21583.60,26.00,68.00,0.00
50%,190555.00,36.00,1.00,28.00,0.00,31669.00,133.00,154.00,0.00
70%,266776.60,47.00,1.00,31.00,1.00,37548.00,152.00,212.00,0.00
90%,342998.20,62.00,1.00,46.00,1.00,48431.00,156.00,270.00,1.00
99%,377297.92,77.00,1.00,50.00,1.00,72963.00,160.00,297.00,1.00
max,381109.00,85.00,1.00,52.00,1.00,540165.00,163.00,299.00,1.00

In [36]:
df.columns

Index(['id', 'Gender', 'Age', 'Driving_License', 'Region_Code',
       'Previously_Insured', 'Vehicle_Age', 'Vehicle_Damage', 'Annual_Premium',
       'Policy_Sales_Channel', 'Vintage', 'Response'],
      dtype='object')

In [37]:
df['id']

0              1
1              2
2              3
3              4
4              5
           ...
381104    381105
381105    381106
381106    381107
381107    381108
381108    381109
Name: id, Length: 381109, dtype: int64

In [38]:
df['Gender']

0           Male
1           Male
2           Male
3           Male
4         Female
           ...
381104      Male
381105      Male
381106      Male
381107    Female
381108      Male
Name: Gender, Length: 381109, dtype: object

In [39]:
# колонки ще можна вибрати ось так
df.id

0              1
1              2
2              3
3              4
4              5
           ...
381104    381105
381105    381106
381106    381107
381107    381108
381108    381109
Name: id, Length: 381109, dtype: int64

In [40]:
df.Gender

0           Male
1           Male
2           Male
3           Male
4         Female
           ...
381104      Male
381105      Male
381106      Male
381107    Female
381108      Male
Name: Gender, Length: 381109, dtype: object

In [41]:
df['Нова колонка'] = 1

In [42]:
df['Нова колонка']

0         1
1         1
2         1
3         1
4         1
         ..
381104    1
381105    1
381106    1
381107    1
381108    1
Name: Нова колонка, Length: 381109, dtype: int64

In [43]:
# не спрацює
df.Нова колонка

SyntaxError: invalid syntax (2874071234.py, line 2)

In [44]:
# Щоб вибрати кілька колонок
df[['Region_Code','Gender']]

        Region_Code  Gender
0              28.0    Male
1               3.0    Male
2              28.0    Male
3              11.0    Male
4              41.0  Female
...             ...     ...
381104         26.0    Male
381105         37.0    Male
381106         30.0    Male
381107         14.0  Female
381108         29.0    Male

[381109 rows x 2 columns]

In [52]:
# створимо новий набір даних і запишемо його в змінну
df_selected_cols = df [['Region_Code', 'Gender', 'Age']]

In [53]:
df_selected_cols

        Region_Code  Gender  Age
0              28.0    Male   44
1               3.0    Male   76
2              28.0    Male   47
3              11.0    Male   21
4              41.0  Female   29
...             ...     ...  ...
381104         26.0    Male   74
381105         37.0    Male   30
381106         30.0    Male   21
381107         14.0  Female   68
381108         29.0    Male   46

[381109 rows x 3 columns]

In [54]:
df_selected_cols[1000:1100]['Gender'][0:10]

1000      Male
1001    Female
1002    Female
1003    Female
1004      Male
1005    Female
1006      Male
1007      Male
1008    Female
1009    Female
Name: Gender, dtype: object

In [55]:
df_selected_cols[1000:1100]['Gender'][0:10].sum() # це просто конкатенація

'MaleFemaleFemaleFemaleMaleFemaleMaleMaleFemaleFemale'

In [58]:
df_selected_cols[1000:1100]['Age'][0:10].sum()

np.int64(371)

In [57]:
df_selected_cols[1000:1100]['Age'][0:10].mean()

np.float64(37.1)

In [61]:
df_selected_cols[1000:1100]['Age'][0:10][0:5:2].astype(str)

1000    49
1002    26
1004    49
Name: Age, dtype: object

In [ ]:
# Перегляд значень в категоріальних колонках

In [63]:
df.select_dtypes('object')

        Gender Vehicle_Age Vehicle_Damage
0         Male   > 2 Years            Yes
1         Male    1-2 Year             No
2         Male   > 2 Years            Yes
3         Male    < 1 Year             No
4       Female    < 1 Year             No
...        ...         ...            ...
381104    Male    1-2 Year             No
381105    Male    < 1 Year             No
381106    Male    < 1 Year             No
381107  Female   > 2 Years            Yes
381108    Male    1-2 Year             No

[381109 rows x 3 columns]

In [65]:
df.select_dtypes('number') # вибирає колонки, які мають числовий тип

,id,Age,Driving_License,Region_Code,Previously_Insured,Annual_Premium,Policy_Sales_Channel,Vintage,Response,Нова колонка
0,1,44,1,28.0,0,40454.0,26.0,217,1,1
1,2,76,1,3.0,0,33536.0,26.0,183,0,1
2,3,47,1,28.0,0,38294.0,26.0,27,1,1
3,4,21,1,11.0,1,28619.0,152.0,203,0,1
4,5,29,1,41.0,1,27496.0,152.0,39,0,1
...,...,...,...,...,...,...,...,...,...,...
381104,381105,74,1,26.0,1,30170.0,26.0,88,0,1
381105,381106,30,1,37.0,1,40016.0,152.0,131,0,1
381106,381107,21,1,30.0,1,35118.0,160.0,161,0,1
381107,381108,68,1,14.0,0,44617.0,124.0,74,0,1
381108,381109,46,1,29.0,0,41777.0,26.0,237,0,1

In [66]:
df.select_dtypes('object').columns  # наші категоріальні колонки

Index(['Gender', 'Vehicle_Age', 'Vehicle_Damage'], dtype='object')

In [67]:
df.Gender.unique()

array(['Male', 'Female'], dtype=object)

In [68]:
df.Gender.nunique()

2

In [69]:
df.Vehicle_Age.unique()

array(['> 2 Years', '1-2 Year', '< 1 Year'], dtype=object)

In [71]:
df.Vehicle_Age.nunique()

3

In [74]:
df.Vehicle_Age.value_counts()

Vehicle_Age
1-2 Year     200316
< 1 Year     164786
> 2 Years     16007
Name: count, dtype: int64

In [75]:
df.Vehicle_Age.value_counts()[['< 1 Year', '> 2 Years']]

Vehicle_Age
< 1 Year     164786
> 2 Years     16007
Name: count, dtype: int64

In [77]:
df.Vehicle_Age.value_counts()[['< 1 Year', '> 2 Years']].sum()

np.int64(180793)

In [78]:
gender_counts = df.Gender.value_counts()

In [79]:
gender_counts

Gender
Male      206089
Female    175020
Name: count, dtype: int64

In [80]:
gender_counts/gender_counts.sum()  # відсоток по статях

Gender
Male      0.540761
Female    0.459239
Name: count, dtype: float64

In [81]:
df.Gender.value_counts(normalize=True)

Gender
Male      0.540761
Female    0.459239
Name: proportion, dtype: float64

In [82]:
example = pd.Series(range(100))

In [83]:
example

0      0
1      1
2      2
3      3
4      4
      ..
95    95
96    96
97    97
98    98
99    99
Length: 100, dtype: int64

In [84]:
example+3

0       3
1       4
2       5
3       6
4       7
     ...
95     98
96     99
97    100
98    101
99    102
Length: 100, dtype: int64

In [88]:
list_example = list(range(3))

In [89]:
list_example+3 # не спрацює

TypeError: can only concatenate list (not "int") to list

In [90]:
list_example*3

[0, 1, 2, 0, 1, 2, 0, 1, 2]