# Домашнє завдання: Внесення оновлень в БД і робота з транзакціями

Це ДЗ передбачене під виконання на локальній машині. Виконання з Google Colab буде суттєво ускладнене.

## Підготовка
1. Переконайтесь, що у вас встановлены необхідні бібліотеки:
   ```bash
   pip install sqlalchemy pymysql pandas matplotlib seaborn python-dotenv
   ```

2. Створіть файл `.env` з параметрами підключення до бази даних classicmodels. Базу даних ви можете отримати через

  - docker-контейнер згідно існтрукції в [документі](https://www.notion.so/hannapylieva/Docker-1eb94835849480c9b2e7f5dc22ee4df9), також відео інструкції присутні на платформі - уроки "MySQL бази, клієнт для роботи з БД, Docker і ChatGPT для запитів" та "Як встановити Docker для роботи з базами даних без терміналу"
  - або встановивши локально цю БД - для цього перегляньте урок "Опціонально. Встановлення MySQL та  БД Сlassicmodels локально".
  
  Приклад `.env` файлу ми створювали в лекції. Ось його обовʼязкове наповнення:
    ```
    DB_HOST=your_host
    DB_PORT=3306 або 3307 - той, який Ви налаштували
    DB_USER=your_username
    DB_PASSWORD=your_password
    DB_NAME=classicmodels
    ```
  Якщо ви створили цей файл під час перегляду лекції - **новий створювати не треба**. Замініть лише назву БД, або пропишіть назву в коді створення підключення (замість отримання назви цільової БД зі змінних оточення). Але переконайтесь, що до `.env` файл лежить в тій самій папці, що і цей ноутбук.

  **УВАГА!** НЕ копіюйте скрит для **створення** `.env` файлу. В лекції він наводиться для прикладу. І давалось пояснення, що в реальних проєктах ми НІКОЛИ не пишемо доступи до бази в коді. Копіювання скрипта для створення `.env` файлу сюди в ДЗ буде вважатись грубою помилкою і ми зніматимемо бали.

3. Налаштуйте підключення через SQLAlchemy до БД за прикладом в лекції.

Рекомендую вивести (відобразити) змінну engine після створення. Вона має бути не None! Якщо None - значить у Вас не підтягнулись налаштування з .env файла.

Ви також можете налаштувати параметри підключення до БД без .env файла, просто прописавши текстом в відповідних місцях. Це - не рекомендований підхід.


## Завдання

### Завдання 1: Оновлення інформації про клієнта (2 бали)

**Створіть функцію для оновлення контактної інформації клієнта за його номером** з наступними можливостями:
- Оновлення телефону клієнта
- Оновлення email (якщо поле існує в таблиці)

Опціонально, якщо вам хочеться більше практики:
- Логування змін в окрему таблицю

Використайте підхід з параметризованими запитами через `text()` та `UPDATE` оператор. Не забудьте на початку перевірити чи існує клієнт з таким номером в базі - це хороша практика.

Отримати всі колонки, які існують в таблиці ви можете наступним запитом
```
  SELECT COLUMN_NAME, DATA_TYPE
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'customers'
```

Запустіть функцію і продемонструйте її роботу, запустивши SELECT, який допоможе це зробити.

In [ ]:
import os

import matplotlib.pyplot as plt
import pandas as pd
import sqlalchemy as sa
from sqlalchemy import create_engine, text
from dotenv import load_dotenv

In [ ]:
# Підключення до БД
def create_connection():
    load_dotenv()

    host = os.getenv('DB_HOST')
    port = os.getenv('DB_PORT', '3306')
    user = os.getenv('DB_USER')
    password = os.getenv('DB_PASSWORD')
    database = os.getenv('DB_NAME')

    connection_string = f"mysql+pymysql://{user}:{password}@{host}:{port}/{database}"

    engine = create_engine(
        connection_string,
        pool_size=1,
        max_overflow=20,
        pool_pre_ping=True,
        echo=False
    )

    return engine

engine = create_connection()

In [ ]:
engine

Engine(mysql+pymysql://root:***@127.0.0.1:3307/classicmodels)

In [ ]:
from sqlalchemy import text
import datetime

def update_customer_contact(engine, customer_number, new_phone=None, new_email=None):
    """
    Оновлює контактну інформацію клієнта
    """
    print(f"🔄 Оновлення інформації для клієнта {customer_number}...")

    # Спочатку перевіряємо структуру таблиці
    print("🔍 Перевіряємо структуру таблиці customers...")
    check_columns_query = text("""
        SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_NAME = 'customers'
        AND COLUMN_NAME IN ('phone', 'email')
        ORDER BY COLUMN_NAME
    """)

    with engine.connect() as conn:
        columns_result = conn.execute(check_columns_query)
        available_columns = {row[0]: {'type': row[1], 'nullable': row[2]} for row in columns_result}

        print("📋 Доступні поля для оновлення:")
        for col, info in available_columns.items():
            print(f"   📌 {col}: {info['type']} ({'nullable' if info['nullable'] == 'YES' else 'not null'})")

        has_email = 'email' in available_columns
        has_phone = 'phone' in available_columns

        if not has_phone:
            print("❌ Поле 'phone' не знайдено в таблиці!")
            return False

    # Перевіряємо чи існує клієнт
    check_query = text("""
        SELECT customerName, phone
        FROM customers
        WHERE customerNumber = :customer_number
    """)

    with engine.connect() as conn:
        with conn.begin():  # Використовуємо транзакцію
            try:
                result = conn.execute(check_query, {'customer_number': customer_number})
                customer = result.fetchone()

                if not customer:
                    print(f"❌ Клієнт {customer_number} не знайдений")
                    return False

                print(f"👤 Клієнт: {customer[0]}")
                print(f"📞 Поточний телефон: {customer[1]}")

                changes_made = []

                # Оновлюємо телефон якщо передано
                if new_phone:
                    old_phone = customer[1]

                    update_phone_query = text("""
                        UPDATE customers
                        SET phone = :new_phone
                        WHERE customerNumber = :customer_number
                    """)

                    conn.execute(update_phone_query, {
                        'new_phone': new_phone,
                        'customer_number': customer_number
                    })

                    changes_made.append(f"Телефон: {old_phone} → {new_phone}")
                    print(f"✅ Телефон оновлено на: {new_phone}")

                # Оновлюємо email якщо поле існує та передано значення
                if new_email:
                    if has_email:
                        # Спочатку отримуємо поточний email якщо він є
                        get_email_query = text("""
                            SELECT email FROM customers
                            WHERE customerNumber = :customer_number
                        """)

                        email_result = conn.execute(get_email_query, {'customer_number': customer_number})
                        current_email_row = email_result.fetchone()
                        old_email = current_email_row[0] if current_email_row else None

                        # Оновлюємо email
                        update_email_query = text("""
                            UPDATE customers
                            SET email = :new_email
                            WHERE customerNumber = :customer_number
                        """)

                        conn.execute(update_email_query, {
                            'new_email': new_email,
                            'customer_number': customer_number
                        })

                        changes_made.append(f"Email: {old_email or '(пусто)'} → {new_email}")
                        print(f"✅ Email оновлено на: {new_email}")

                    else:
                        print("⚠️ Поле 'email' не існує в таблиці customers - пропускаємо оновлення")

                if changes_made:
                    print(f"🎉 Оновлення завершено для клієнта {customer[0]}")
                    print(f"📝 Зміни: {'; '.join(changes_made)}")
                else:
                    print("ℹ️ Не було передано даних для оновлення")

                return True

            except Exception as e:
                print(f"❌ Помилка при оновленні: {e}")
                print("🔄 Всі зміни автоматично скасовано (ROLLBACK)")
                return False

# Тестуємо функцію
print("=== ТЕСТ 1: Оновлення тільки телефону ===")
customer_id = 103  # Atelier graphique
success1 = update_customer_contact(
    engine,
    customer_id,
    new_phone="+33 1 42 34 56 78"
)

print("\n=== ТЕСТ 2: Спроба оновлення email (перевіримо чи існує поле) ===")
success2 = update_customer_contact(
    engine,
    customer_id,
    new_phone="+33 1 42 34 56 99",
    new_email="contact@atelier-graphique.fr"
)

# Перевіряємо результат
if success1 or success2:
    print("\n📋 Оновлена інформація про клієнта:")
    verification_query = text("""
        SELECT customerName, phone, contactFirstName, contactLastName
        FROM customers
        WHERE customerNumber = :customer_number
    """)

    df_updated = pd.read_sql(verification_query, engine, params={'customer_number': customer_id})
    display(df_updated)

=== ТЕСТ 1: Оновлення тільки телефону ===
🔄 Оновлення інформації для клієнта 103...
🔍 Перевіряємо структуру таблиці customers...
📋 Доступні поля для оновлення:
   📌 phone: varchar (not null)
👤 Клієнт: Atelier graphique
📞 Поточний телефон: +33 1 42 35 00 00
✅ Телефон оновлено на: +33 1 42 34 56 78
🎉 Оновлення завершено для клієнта Atelier graphique
📝 Зміни: Телефон: +33 1 42 35 00 00 → +33 1 42 34 56 78

=== ТЕСТ 2: Спроба оновлення email (перевіримо чи існує поле) ===
🔄 Оновлення інформації для клієнта 103...
🔍 Перевіряємо структуру таблиці customers...
📋 Доступні поля для оновлення:
   📌 phone: varchar (not null)
👤 Клієнт: Atelier graphique
📞 Поточний телефон: +33 1 42 34 56 78
✅ Телефон оновлено на: +33 1 42 34 56 99
⚠️ Поле 'email' не існує в таблиці customers - пропускаємо оновлення
🎉 Оновлення завершено для клієнта Atelier graphique
📝 Зміни: Телефон: +33 1 42 34 56 78 → +33 1 42 34 56 99

📋 Оновлена інформація про клієнта:

        customerName              phone contactFirstName contactLastName
0  Atelier graphique  +33 1 42 34 56 99          Carine          Schmitt

In [ ]:
# Опціонально: Версія з логуванням
def update_customer_contact_with_logging(engine, customer_number, new_phone=None, new_email=None):
    """
    Розширена версія з логуванням змін
    """
    print(f"🔄 Оновлення з логуванням для клієнта {customer_number}...")

    # Створюємо таблицю логування якщо не існує
    create_log_table = text("""
        CREATE TABLE IF NOT EXISTS customer_changes_log (
            id INT AUTO_INCREMENT PRIMARY KEY,
            customer_number INT NOT NULL,
            field_name VARCHAR(50) NOT NULL,
            old_value VARCHAR(255),
            new_value VARCHAR(255),
            change_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            changed_by VARCHAR(50) DEFAULT 'system'
        )
    """)

    with engine.connect() as conn:
        conn.execute(create_log_table)
        conn.commit()

    # Перевіряємо структуру таблиці
    check_columns_query = text("""
        SELECT COLUMN_NAME
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'customers'
        AND COLUMN_NAME IN ('phone', 'email')
    """)

    with engine.connect() as conn:
        with conn.begin():
            try:
                columns_result = conn.execute(check_columns_query)
                available_columns = [row[0] for row in columns_result]
                has_email = 'email' in available_columns

                # Отримуємо поточні дані клієнта
                if has_email:
                    check_query = text("""
                        SELECT customerName, phone, email
                        FROM customers
                        WHERE customerNumber = :customer_number
                    """)
                else:
                    check_query = text("""
                        SELECT customerName, phone, NULL as email
                        FROM customers
                        WHERE customerNumber = :customer_number
                    """)

                result = conn.execute(check_query, {'customer_number': customer_number})
                customer = result.fetchone()

                if not customer:
                    print(f"❌ Клієнт {customer_number} не знайдений")
                    return False

                print(f"👤 Клієнт: {customer[0]}")

                # Функція для логування
                def log_change(field_name, old_value, new_value):
                    log_query = text("""
                        INSERT INTO customer_changes_log
                        (customer_number, field_name, old_value, new_value)
                        VALUES (:customer_number, :field_name, :old_value, :new_value)
                    """)
                    conn.execute(log_query, {
                        'customer_number': customer_number,
                        'field_name': field_name,
                        'old_value': str(old_value) if old_value else None,
                        'new_value': str(new_value)
                    })

                changes_logged = []

                # Оновлюємо телефон
                if new_phone:
                    old_phone = customer[1]

                    update_phone_query = text("""
                        UPDATE customers
                        SET phone = :new_phone
                        WHERE customerNumber = :customer_number
                    """)

                    conn.execute(update_phone_query, {
                        'new_phone': new_phone,
                        'customer_number': customer_number
                    })

                    log_change('phone', old_phone, new_phone)
                    changes_logged.append('phone')
                    print(f"✅ Телефон оновлено та залоговано: {new_phone}")

                # Оновлюємо email
                if new_email:
                    if has_email:
                        old_email = customer[2]

                        update_email_query = text("""
                            UPDATE customers
                            SET email = :new_email
                            WHERE customerNumber = :customer_number
                        """)

                        conn.execute(update_email_query, {
                            'new_email': new_email,
                            'customer_number': customer_number
                        })

                        log_change('email', old_email, new_email)
                        changes_logged.append('email')
                        print(f"✅ Email оновлено та залоговано: {new_email}")
                    else:
                        print("⚠️ Поле email не існує - логуємо спробу оновлення")
                        log_change('email_attempt', None, new_email)

                print(f"🎉 Оновлення завершено! Залоговано змін: {len(changes_logged)}")
                return True

            except Exception as e:
                print(f"❌ Помилка: {e}")
                return False

# Демонстрація версії з логуванням
print("\n\n=== ТЕСТ 3: З логуванням ===")
success3 = update_customer_contact_with_logging(
    engine,
    103,
    new_phone="+33 1 42 35 00 00",
    new_email="newemail@atelier.com"
)

if success3:
    # Показуємо лог змін
    log_query = text("""
        SELECT customer_number, field_name, old_value, new_value, change_date
        FROM customer_changes_log
        WHERE customer_number = :customer_number
        ORDER BY change_date DESC
        LIMIT 5
    """)

    try:
        df_log = pd.read_sql(log_query, engine, params={'customer_number': 103})
        print("\n📜 Останні записи в логу:")
        display(df_log)
    except Exception as e:
        print(f"⚠️ Таблиця логування не створена або недоступна: {e}")

=== ТЕСТ 3: З логуванням ===
🔄 Оновлення з логуванням для клієнта 103...
👤 Клієнт: Atelier graphique
✅ Телефон оновлено та залоговано: +33 1 42 35 00 00
⚠️ Поле email не існує - логуємо спробу оновлення
🎉 Оновлення завершено! Залоговано змін: 1

📜 Останні записи в логу:

,customer_number,field_name,old_value,new_value,change_date
0,103,phone,+33 1 42 34 56 99,+33 1 42 35 00 00,2025-08-13 16:16:38
1,103,email_attempt,None,newemail@atelier.com,2025-08-13 16:16:38
2,103,phone,+33 1 42 34 56 99,+33 1 42 35 00 00,2025-08-13 16:15:03
3,103,email_attempt,None,newemail@atelier.com,2025-08-13 16:15:03
4,103,phone,+33 1 42 34 56 78,+33 1 42 34 56 99,2025-08-13 16:10:51

### Завдання 2: Створення нового замовлення з транзакцією (5 балів)

**Реалізуйте процес створення нового замовлення** з наступними кроками в одній транзакції:
- Створення запису в таблиці `orders`
- Додавання товарних позицій в `orderdetails`
- Перевірка наявності товарів на складі
- Зменшення кількості товарів на складі

Запустіть процес з тестовими даними і продемонструйте через SELECT, що процес успішно відпрацював і були виконані необхідні операції.

In [ ]:
def create_new_order(engine, customer_number, order_items):
    """
    Створює нове замовлення з товарними позиціями в транзакції

    order_items: список словників [{'productCode': 'S10_1678', 'quantity': 2, 'price': 95.70}, ...]
    """
    print(f"🛒 Створення замовлення для клієнта {customer_number}...")

    with engine.connect() as conn:
        with conn.begin():  # Початок транзакції
            try:
                # Крок 1: Перевіряємо клієнта
                check_customer_query = text("""
                    SELECT customerName FROM customers
                    WHERE customerNumber = :customer_number
                """)

                result = conn.execute(check_customer_query, {'customer_number': customer_number})
                customer = result.fetchone()

                if not customer:
                    raise Exception(f"Клієнт {customer_number} не знайдений")

                print(f"👤 Клієнт: {customer[0]}")

                # Крок 2: Генеруємо новий номер замовлення
                get_max_order_query = text("SELECT MAX(orderNumber) FROM orders")
                result = conn.execute(get_max_order_query)
                max_order = result.fetchone()[0]
                new_order_number = max_order + 1

                print(f"📋 Новий номер замовлення: {new_order_number}")

                # Крок 3: Перевіряємо наявність товарів на складі
                total_amount = 0
                for item in order_items:
                    check_stock_query = text("""
                        SELECT productName, quantityInStock, buyPrice
                        FROM products
                        WHERE productCode = :product_code
                    """)

                    result = conn.execute(check_stock_query, {'product_code': item['productCode']})
                    product = result.fetchone()

                    if not product:
                        raise Exception(f"Товар {item['productCode']} не знайдений")

                    if product[1] < item['quantity']:
                        raise Exception(f"Недостатньо товару {product[0]} на складі. Доступно: {product[1]}, потрібно: {item['quantity']}")

                    total_amount += item['quantity'] * item['price']
                    print(f"✅ {product[0]}: {item['quantity']} шт. по ${item['price']}")

                # Крок 4: Створюємо замовлення
                create_order_query = text("""
                    INSERT INTO orders (orderNumber, orderDate, requiredDate, status, customerNumber)
                    VALUES (:order_number, :order_date, :required_date, :status, :customer_number)
                """)

                order_date = datetime.date.today()
                required_date = order_date + datetime.timedelta(days=14)

                conn.execute(create_order_query, {
                    'order_number': new_order_number,
                    'order_date': order_date,
                    'required_date': required_date,
                    'status': 'In Process',
                    'customer_number': customer_number
                })

                print(f"✅ Замовлення {new_order_number} створено")

                # Крок 5: Додаємо товарні позиції
                add_orderdetail_query = text("""
                    INSERT INTO orderdetails (orderNumber, productCode, quantityOrdered, priceEach, orderLineNumber)
                    VALUES (:order_number, :product_code, :quantity, :price, :line_number)
                """)

                for i, item in enumerate(order_items, 1):
                    conn.execute(add_orderdetail_query, {
                        'order_number': new_order_number,
                        'product_code': item['productCode'],
                        'quantity': item['quantity'],
                        'price': item['price'],
                        'line_number': i
                    })

                print(f"✅ Додано {len(order_items)} товарних позицій")

                # Крок 6: Зменшуємо кількість на складі
                update_stock_query = text("""
                    UPDATE products
                    SET quantityInStock = quantityInStock - :quantity
                    WHERE productCode = :product_code
                """)

                for item in order_items:
                    conn.execute(update_stock_query, {
                        'quantity': item['quantity'],
                        'product_code': item['productCode']
                    })

                print(f"✅ Оновлено залишки на складі")
                print(f"💰 Загальна сума замовлення: ${total_amount:,.2f}")
                print(f"🎉 Замовлення {new_order_number} успішно створено!")

                return new_order_number

            except Exception as e:
                print(f"❌ Помилка при створенні замовлення: {e}")
                print("🔄 Всі зміни автоматично скасовано (ROLLBACK)")
                return None

In [ ]:
# Тестуємо створення замовлення
test_order_items = [
    {'productCode': 'S10_1678', 'quantity': 2, 'price': 95.70},
    {'productCode': 'S10_2016', 'quantity': 1, 'price': 120.50}
]

new_order_id = create_new_order(engine, 103, test_order_items)

if new_order_id:
    # Перевіряємо створене замовлення
    verification_query = text("""
        SELECT
            o.orderNumber,
            o.orderDate,
            o.status,
            c.customerName,
            od.productCode,
            p.productName,
            od.quantityOrdered,
            od.priceEach,
            (od.quantityOrdered * od.priceEach) as total_price
        FROM orders o
        JOIN customers c ON o.customerNumber = c.customerNumber
        JOIN orderdetails od ON o.orderNumber = od.orderNumber
        JOIN products p ON od.productCode = p.productCode
        WHERE o.orderNumber = :order_number
    """)

    df_new_order = pd.read_sql(verification_query, engine, params={'order_number': new_order_id})
    print("\nДеталі створеного замовлення:")
    display(df_new_order)

🛒 Створення замовлення для клієнта 103...
👤 Клієнт: Atelier graphique
📋 Новий номер замовлення: 10426
✅ 1969 Harley Davidson Ultimate Chopper: 2 шт. по $95.7
✅ 1996 Moto Guzzi 1100i: 1 шт. по $120.5
✅ Замовлення 10426 створено
✅ Додано 2 товарних позицій
✅ Оновлено залишки на складі
💰 Загальна сума замовлення: $311.90
🎉 Замовлення 10426 успішно створено!

Деталі створеного замовлення:

,orderNumber,orderDate,status,customerName,productCode,productName,quantityOrdered,priceEach,total_price
0,10426,2025-07-23,In Process,Atelier graphique,S10_1678,1969 Harley Davidson Ultimate Chopper,2,95.7,191.4
1,10426,2025-07-23,In Process,Atelier graphique,S10_2016,1996 Moto Guzzi 1100i,1,120.5,120.5