In [1]:
import pandas as pd

In [3]:
pd.__version__   # переглядає яка версія Pandas

'2.2.3'

## GroupBy

In [8]:
# Створення словника, де для кожної назви стовпця прописано список значень, і перетворити цей словник на таблицю Pandas
df = pd.DataFrame({
    "A": [7, 7, 5, 1, 1, 5, 1, 9, 1, 8, 5, 7, 3, 4, 3, 7, 7, 6, 9, 7],
    "B": [1, 2, 3, 1, 1, 2, 4, 1, 3, 4, 4, 3, 3, 4, 1, 3, 4, 3, 4, 1],
    "C": ['green', 'green', 'red', 'blue', 'blue', 'green', 'red', 'red',
       'blue', 'green', 'red', 'green', 'blue', 'red', 'blue', 'blue',
       'blue', 'green', 'green', 'red']
})

In [12]:
df.head()

   A  B      C
0  7  1  green
1  7  2  green
2  5  3    red
3  1  1   blue
4  1  1   blue

In [14]:
grouped= df.groupby('A')   # Групування за стовпцем "A"

In [15]:
# Показуємо згруповані дані
grouped

In [16]:
grouped.size()  # повертає кількість елементів у кожній групі

A
1    4
3    2
4    1
5    3
6    1
7    6
8    1
9    2
dtype: int64

In [19]:
# Перевіряємо кількість рядків у стовпці 'A', де значення дорівнює 1
df[df.A==1].shape[0]

4

In [28]:
# Перевіряємо кількість рядків у стовпці 'A', де значення дорівнює 7
df[df.A==7].shape[0]

6

In [31]:
grouped.mean()   # помилка: не вказали колонки

TypeError: agg function failed [how->mean,dtype->object]

In [26]:
df[df.A==1].B  # Покажи  всі числа зі стовпця B, які стоять навпроти одиниць у стовпці A

3    1
4    1
6    4
8    3
Name: B, dtype: int64

In [27]:
df[df.A==1].B.mean()   # обчислює середнє арифметичне значення стовпця 'B' лише для тих рядків, де у стовпці 'A' стоїть одиниця
#1+1+4+3= 9/4= 2.25

np.float64(2.25)

In [32]:
# Виправляємо помилку. Рахуємо середнє
grouped.mean(numeric_only=True)

          B
A
1  2.250000
3  2.000000
4  4.000000
5  3.000000
6  3.000000
7  2.333333
8  4.000000
9  2.500000

In [36]:
grouped['B'].mean()  # Обчислення середнього значення стовпця 'B' для кожної групи зі стовпця 'A'

A
1    2.250000
3    2.000000
4    4.000000
5    3.000000
6    3.000000
7    2.333333
8    4.000000
9    2.500000
Name: B, dtype: float64

In [38]:
df.groupby('A').min()

   B      C
A
1  1   blue
3  1   blue
4  4    red
5  2  green
6  3  green
7  1   blue
8  4  green
9  1  green

In [41]:
df.groupby('A').describe()  # Згрупуй таблицю за стовпцем 'A' і виведи повний набір описової статистики для всіх числових стовпців

      B
  count      mean       std  min   25%  50%   75%  max
A
1   4.0  2.250000  1.500000  1.0  1.00  2.0  3.25  4.0
3   2.0  2.000000  1.414214  1.0  1.50  2.0  2.50  3.0
4   1.0  4.000000       NaN  4.0  4.00  4.0  4.00  4.0
5   3.0  3.000000  1.000000  2.0  2.50  3.0  3.50  4.0
6   1.0  3.000000       NaN  3.0  3.00  3.0  3.00  3.0
7   6.0  2.333333  1.211060  1.0  1.25  2.5  3.00  4.0
8   1.0  4.000000       NaN  4.0  4.00  4.0  4.00  4.0
9   2.0  2.500000  2.121320  1.0  1.75  2.5  3.25  4.0

In [43]:
df.groupby('A').agg('max')   # Згрупуй дані за стовпцем 'A' і обчисли максимальне значення для кожного іншого стовпця

   B      C
A
1  4    red
3  3   blue
4  4    red
5  4    red
6  3  green
7  4    red
8  4  green
9  4    red

In [44]:
df.groupby('A')['B'].agg(['size', 'max', 'min','mean', 'std'])

   size  max  min      mean       std
A
1     4    4    1  2.250000  1.500000
3     2    3    1  2.000000  1.414214
4     1    4    4  4.000000       NaN
5     3    4    2  3.000000  1.000000
6     1    3    3  3.000000       NaN
7     6    4    1  2.333333  1.211060
8     1    4    4  4.000000       NaN
9     2    4    1  2.500000  2.121320

In [46]:
def min_minus_one(values):
    return values.min()-1

In [48]:
df.groupby('A')['B'].agg(min_minus_one)   # Для кожної групи значень 'A' знайди мінімум у стовпці 'B' і відніми від нього 1

A
1    0
3    0
4    3
5    1
6    2
7    0
8    3
9    0
Name: B, dtype: int64

In [49]:
# Як перевірити себе?
df[df.A==1].B

3    1
4    1
6    4
8    3
Name: B, dtype: int64

df.groupby('A'): Ми ділимо таблицю на групи за унікальними числами в стовпці 'A'.

.agg({ ... }): Ми передаємо словник, де вказуємо «завдання» для кожного стовпця окремо:

'B': max — для стовпця 'B' знайти лише максимальне значення.

'C': [pd.Series.mode] — для стовпця 'C' (текст) знайти моду

In [54]:
df.groupby('A').agg({'B': max, 'C': [pd.Series.mode]})

C:\Users\PC\AppData\Local\Temp\ipykernel_19120\4073082595.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby('A').agg({'B': max, 'C': [pd.Series.mode]})

    B             C
  max          mode
A
1   4          blue
3   3          blue
4   4           red
5   4           red
6   3         green
7   4         green
8   4         green
9   4  [green, red]

## Функція pivot()

In [55]:
df = pd.DataFrame({'foo': ['one', 'one', 'one', 'two', 'two', 'two'],
                    'bar': ['A', 'B', 'C', 'A', 'B', 'C'],
                    'baz': [1, 2, 3, 4, 5, 6],
                    'zoo': ['x', 'y', 'z', 'q', 'w', 't']})

In [56]:
df

   foo bar  baz zoo
0  one   A    1   x
1  one   B    2   y
2  one   C    3   z
3  two   A    4   q
4  two   B    5   w
5  two   C    6   t

In [57]:
# Створюємо новий датафрейм, групований за стовпцем "A"
pivoted= df.pivot(index='foo', columns='bar', values = 'baz')

In [58]:
pivoted

bar  A  B  C
foo
one  1  2  3
two  4  5  6

In [60]:
df.pivot(index='foo', columns= 'bar') #якщо не вкажемо values

    baz       zoo
bar   A  B  C   A  B  C
foo
one   1  2  3   x  y  z
two   4  5  6   q  w  t

## Функція pivot_table()

In [62]:
df = pd.DataFrame({"A": ["foo", "foo", "foo", "foo", "foo",
                          "bar", "bar", "bar", "bar"],
                    "B": ["one", "one", "one", "two", "two",
                          "one", "one", "two", "two"],
                    "C": ["small", "large", "large", "small",
                          "small", "large", "small", "small",
                          "large"],
                    "D": [1, 2, 2, 3, 3, 4, 5, 6, 7],
                    "E": [2, 4, 5, 5, 6, 6, 8, 9, 9]})

In [63]:
df

     A    B      C  D  E
0  foo  one  small  1  2
1  foo  one  large  2  4
2  foo  one  large  2  5
3  foo  two  small  3  5
4  foo  two  small  3  6
5  bar  one  large  4  6
6  bar  one  small  5  8
7  bar  two  small  6  9
8  bar  two  large  7  9

In [64]:
res1=pd.pivot_table(df, index='A', columns= 'C', values= 'D', aggfunc= 'sum')

In [65]:
res1

C    large  small
A
bar     11     11
foo      4      7

In [66]:
res2 = pd.pivot_table(df, index='A', columns= 'C', values= 'D', aggfunc= list)
res2   # aggfunc=list: Замість того, щоб рахувати суму чи середнє, Pandas просто збирає всі знайдені числа в список і кладе їх у відповідну клітинку

C     large      small
A
bar  [4, 7]     [5, 6]
foo  [2, 2]  [1, 3, 3]

In [67]:
res3 = pd.pivot_table(df, index='A', columns='C', values=['D'], aggfunc="sum")
res3

        D
C   large small
A
bar    11    11
foo     4     7

In [68]:
display(res1.columns, res3.columns)

Index(['large', 'small'], dtype='object', name='C')

MultiIndex([('D', 'large'),
            ('D', 'small')],
           names=[None, 'C'])

In [69]:
# Як позбутися MultiIndex
res3.columns.droplevel(0)

Index(['large', 'small'], dtype='object', name='C')

In [70]:
res3.columns = res3.columns.droplevel(0)

In [71]:
res3

C    large  small
A
bar     11     11
foo      4      7

In [73]:
display(res1.columns, res3.columns)  # Візуальна перевірка та порівняння структур стовпців обох таблиць

Index(['large', 'small'], dtype='object', name='C')

Index(['large', 'small'], dtype='object', name='C')

In [78]:
df.sort_values(['A', 'B', 'C'])

     A    B      C  D  E
5  bar  one  large  4  6
6  bar  one  small  5  8
8  bar  two  large  7  9
7  bar  two  small  6  9
1  foo  one  large  2  4
2  foo  one  large  2  5
0  foo  one  small  1  2
3  foo  two  small  3  5
4  foo  two  small  3  6

In [81]:
pd.pivot(df.drop_duplicates(subset=['A', 'B', 'C']), index=['A', 'B'], columns=['C'], values='D')

C        large  small
A   B
bar one    4.0    5.0
    two    7.0    6.0
foo one    2.0    1.0
    two    NaN    3.0

In [83]:
df

     A    B      C  D  E
0  foo  one  small  1  2
1  foo  one  large  2  4
2  foo  one  large  2  5
3  foo  two  small  3  5
4  foo  two  small  3  6
5  bar  one  large  4  6
6  bar  one  small  5  8
7  bar  two  small  6  9
8  bar  two  large  7  9

In [85]:
df.drop_duplicates(subset=['A', 'B', 'C'])

     A    B      C  D  E
0  foo  one  small  1  2
1  foo  one  large  2  4
3  foo  two  small  3  5
5  bar  one  large  4  6
6  bar  one  small  5  8
7  bar  two  small  6  9
8  bar  two  large  7  9

In [86]:
pd.pivot_table(df, values=['D', 'E'], index=['A', 'C'],
               aggfunc= {
                   'D': 'mean',
                   'E': ['min', 'max', 'mean']
               }
              )

                  D   E
               mean max      mean min
A   C
bar large  5.500000   9  7.500000   6
    small  5.500000   9  8.500000   8
foo large  2.000000   5  4.500000   4
    small  2.333333   6  4.333333   2