In [1]:
import pandas as pd
import numpy as np

In [2]:
df= pd.read_csv('health_insurance_cross_sell_prediction.csv')

In [3]:
df[df.Gender=='Male'].Age.describe()

count    206089.000000
mean         40.903095
std          15.449718
min          20.000000
25%          26.000000
50%          41.000000
75%          52.000000
max          85.000000
Name: Age, dtype: float64

In [4]:
df[df.Gender=='Female'].Age.describe()

count    175020.000000
mean         36.372746
std          15.223969
min          20.000000
25%          24.000000
50%          30.000000
75%          46.000000
max          85.000000
Name: Age, dtype: float64

In [5]:
df.columns

Index(['id', 'Gender', 'Age', 'Driving_License', 'Region_Code',
       'Previously_Insured', 'Vehicle_Age', 'Vehicle_Damage', 'Annual_Premium',
       'Policy_Sales_Channel', 'Vintage', 'Response'],
      dtype='object')

In [6]:
filter_1 = (df.Gender=='Male') & (df.Age >= 26) & (df.Age <=52)
df[filter_1].Response.value_counts(normalize=True)

Response
0    0.815225
1    0.184775
Name: proportion, dtype: float64

In [7]:
filter_2= (df.Gender=='Male') & ((df.Age < 26) | (df.Age > 52))
df[filter_2].Response.value_counts(normalize=True)

Response
0    0.911723
1    0.088277
Name: proportion, dtype: float64

In [8]:
df.query('Gender == "Male" & Age >= 26 & Age <= 52').Response.value_counts(normalize=True)

Response
0    0.815225
1    0.184775
Name: proportion, dtype: float64

In [9]:
df.query('Gender == "Male" & ((Age < 26) | (Age > 52))').Response.value_counts(normalize=True)

Response
0    0.911723
1    0.088277
Name: proportion, dtype: float64

In [10]:
df.sort_values(by="Age").head()

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
67915,67916,Male,20,1,24.0,0,< 1 Year,Yes,27448.0,160.0,259,0
6316,6317,Male,20,1,27.0,1,< 1 Year,No,2630.0,160.0,69,0
193265,193266,Female,20,1,42.0,0,< 1 Year,Yes,2630.0,160.0,20,0
374102,374103,Male,20,1,8.0,1,< 1 Year,No,35073.0,160.0,241,0
6332,6333,Male,20,1,17.0,0,< 1 Year,Yes,30618.0,160.0,151,0

In [11]:
df.sort_values(by="Age", ascending=False).head() # сортуємо за спаданням колонки Age

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
48875,48876,Female,85,1,45.0,1,1-2 Year,No,2630.0,26.0,102,0
213099,213100,Female,85,1,28.0,0,1-2 Year,Yes,2630.0,26.0,290,0
150129,150130,Male,85,1,48.0,0,1-2 Year,Yes,2630.0,124.0,37,0
210249,210250,Female,85,1,28.0,1,1-2 Year,No,42530.0,26.0,64,0
137703,137704,Female,85,1,28.0,0,1-2 Year,Yes,51045.0,124.0,147,0

In [12]:
df.sort_values(by="Age", ascending=False)[:20]  # виведе 20 записів відсортованих по колонці Вік за спаданням

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
48875,48876,Female,85,1,45.0,1,1-2 Year,No,2630.0,26.0,102,0
213099,213100,Female,85,1,28.0,0,1-2 Year,Yes,2630.0,26.0,290,0
150129,150130,Male,85,1,48.0,0,1-2 Year,Yes,2630.0,124.0,37,0
210249,210250,Female,85,1,28.0,1,1-2 Year,No,42530.0,26.0,64,0
137703,137704,Female,85,1,28.0,0,1-2 Year,Yes,51045.0,124.0,147,0
100683,100684,Female,85,1,28.0,0,1-2 Year,Yes,32366.0,26.0,293,0
321081,321082,Female,85,1,8.0,1,1-2 Year,No,41080.0,7.0,129,0
181135,181136,Male,85,1,28.0,0,1-2 Year,Yes,34005.0,122.0,279,0
109851,109852,Female,85,1,50.0,0,1-2 Year,Yes,26475.0,124.0,114,0
208264,208265,Female,85,1,8.0,0,1-2 Year,Yes,65268.0,124.0,245,0
229103,229104,Female,85,0,28.0,1,1-2 Year,No,27057.0,26.0,65,0
47828,47829,Female,84,1,28.0,1,1-2 Year,Yes,43889.0,26.0,181,0
617,618,Male,84,1,28.0,1,1-2 Year,No,49367.0,122.0,31,0
49955,49956,Male,84,1,16.0,1,1-2 Year,No,26748.0,26.0,94,0
274627,274628,Female,84,1,28.0,1,1-2 Year,No,38076.0,26.0,173,0
304381,304382,Female,84,1,1.0,1,1-2 Year,No,2630.0,26.0,178,0
21886,21887,Male,84,1,47.0,1,1-2 Year,No,35228.0,124.0,136,0
169290,169291,Male,84,0,40.0,1,1-2 Year,No,2630.0,26.0,52,0
221845,221846,Female,84,1,28.0,0,1-2 Year,No,55326.0,122.0,147,0
130147,130148,Female,84,1,28.0,0,1-2 Year,Yes,52241.0,26.0,217,0

In [13]:
# відсортуй за колонками Age за зростанням та Annual_Premium за спаданням і виведи перші 5 записів
df.sort_values(by=["Age", "Annual_Premium"], ascending=[True, False]).head()

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
71046,71047,Female,20,1,47.0,0,< 1 Year,No,152866.0,160.0,285,0
165841,165842,Female,20,1,28.0,1,< 1 Year,No,117057.0,160.0,172,0
199087,199088,Male,20,1,13.0,0,< 1 Year,Yes,100227.0,160.0,11,0
58455,58456,Female,20,1,36.0,0,< 1 Year,Yes,99950.0,160.0,14,0
275348,275349,Female,20,1,28.0,0,1-2 Year,Yes,99021.0,26.0,90,0

In [14]:
# відсортуй за колонками Age за спаданням та Previously_Insured за спаданням і виведи 3 перші записи

df.sort_values(by=["Age", "Previously_Insured"], ascending=[False, False]).head(3)

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
48875,48876,Female,85,1,45.0,1,1-2 Year,No,2630.0,26.0,102,0
210249,210250,Female,85,1,28.0,1,1-2 Year,No,42530.0,26.0,64,0
229103,229104,Female,85,0,28.0,1,1-2 Year,No,27057.0,26.0,65,0

In [15]:
df.sort_index(axis=1).head() # назви колонок таблиці відсортовано в алфавітному порядку

,Age,Annual_Premium,Driving_License,Gender,Policy_Sales_Channel,Previously_Insured,Region_Code,Response,Vehicle_Age,Vehicle_Damage,Vintage,id
0,44,40454.0,1,Male,26.0,0,28.0,1,> 2 Years,Yes,217,1
1,76,33536.0,1,Male,26.0,0,3.0,0,1-2 Year,No,183,2
2,47,38294.0,1,Male,26.0,0,28.0,1,> 2 Years,Yes,27,3
3,21,28619.0,1,Male,152.0,1,11.0,0,< 1 Year,No,203,4
4,29,27496.0,1,Female,152.0,1,41.0,0,< 1 Year,No,39,5

In [16]:
# створення нової колонки
df["New_col"]=3/10
df["New_col"]

0         0.3
1         0.3
2         0.3
3         0.3
4         0.3
         ...
381104    0.3
381105    0.3
381106    0.3
381107    0.3
381108    0.3
Name: New_col, Length: 381109, dtype: float64

In [17]:
import random
values = [random.choice([1,2,3]) for _ in range(len(df))]

In [18]:
df['random_category']= values

In [19]:
df['new_cat']=df.random_category+1

In [20]:
df[['new_cat','random_category']]

        new_cat  random_category
0             4                3
1             3                2
2             2                1
3             2                1
4             4                3
...         ...              ...
381104        3                2
381105        3                2
381106        3                2
381107        3                2
381108        4                3

[381109 rows x 2 columns]

In [21]:
df['new_cat']=df.random_category.apply(lambda x: 'Small' if x<1 else 'Big')

In [22]:
df[['random_category', 'new_cat']].head()

   random_category new_cat
0                3     Big
1                2     Big
2                1     Big
3                1     Big
4                3     Big

In [23]:
add_ten = lambda x,y: x+y+10
print(add_ten(5,2))

17

In [24]:
my_lambda = lambda x: 'Small' if x<1 else 'Big'
my_lambda(5)

'Big'

In [25]:
my_lambda = lambda x: 'Small' if x<1 else 'Big'
my_lambda(0)

'Small'

In [26]:
numbers = [1,2,3,4,5]
squared = map(lambda x: x**2, numbers)
print(list(squared))

[1, 4, 9, 16, 25]

In [27]:
def category_mapping(val):
    if val== 1:
        return 'Small'
    elif val== 2:
        return 'Medium'
    else:
        return 'Large'

In [28]:
df['new_cat']= df.random_category.apply(lambda x: category_mapping(x))
df[['random_category', 'new_cat']].head()

   random_category new_cat
0                3   Large
1                2  Medium
2                1   Small
3                1   Small
4                3   Large

In [29]:
df['new_cat'] = df.random_category.apply(category_mapping)
df[['random_category', 'new_cat']].head()

   random_category new_cat
0                3   Large
1                2  Medium
2                1   Small
3                1   Small
4                3   Large

## Порівняння колонок

In [30]:
df['new_cat']

0          Large
1         Medium
2          Small
3          Small
4          Large
           ...
381104    Medium
381105    Medium
381106    Medium
381107    Medium
381108     Large
Name: new_cat, Length: 381109, dtype: object

In [31]:
df['new_cat'] == 'Small'

0         False
1         False
2          True
3          True
4         False
          ...
381104    False
381105    False
381106    False
381107    False
381108    False
Name: new_cat, Length: 381109, dtype: bool

In [32]:
df['new_cat'] != 'Small'

0          True
1          True
2         False
3         False
4          True
          ...
381104     True
381105     True
381106     True
381107     True
381108     True
Name: new_cat, Length: 381109, dtype: bool

In [33]:
df['new_cat'] <= 'Small'

0         True
1         True
2         True
3         True
4         True
          ...
381104    True
381105    True
381106    True
381107    True
381108    True
Name: new_cat, Length: 381109, dtype: bool

In [34]:
df['new_cat_dublicate'] = df['new_cat']

In [35]:
# порівняння колонок між собою
df['new_cat_dublicate'] == df['new_cat']

0         True
1         True
2         True
3         True
4         True
          ...
381104    True
381105    True
381106    True
381107    True
381108    True
Length: 381109, dtype: bool

In [36]:
np.isclose(0.1 + 0.2, 0.3) #Функція перевіряє, чи числа достатньо близькі, а не ідеально рівні (з урахуванням похибки)

np.True_

## Перетворення типу колонки

In [37]:
df.random_category.head()

0    3
1    2
2    1
3    1
4    3
Name: random_category, dtype: int64

In [40]:
df['random_category_str'] = df.random_category.astype(str)  # з колонки random_category хочемо зробити str

In [41]:
df[['random_category', 'random_category_str']].dtypes  # повертає типи даних (dtype) для двох колонок у DataFrame df

random_category         int64
random_category_str    object
dtype: object

In [42]:
type(df.random_category_str.loc[0])  # повертає тип конкретного значення (елемента) з колонки random_category_str у рядку з індексом 0

str

In [43]:
df['new_cat']

0          Large
1         Medium
2          Small
3          Small
4          Large
           ...
381104    Medium
381105    Medium
381106    Medium
381107    Medium
381108     Large
Name: new_cat, Length: 381109, dtype: object

In [46]:
 # створює нову колонку new_cat_cat, де дані з new_cat перетворені у категоріальний тип (category)
df['new_cat_cat'] = df.new_cat.astype('category')

In [47]:
df['new_cat_cat']

0          Large
1         Medium
2          Small
3          Small
4          Large
           ...
381104    Medium
381105    Medium
381106    Medium
381107    Medium
381108     Large
Name: new_cat_cat, Length: 381109, dtype: category
Categories (3, object): ['Large', 'Medium', 'Small']

In [49]:
df[['new_cat_cat', 'new_cat']].memory_usage()   # показує, скільки пам’яті займають ці дві колонки (у байтах)

Index              132
new_cat_cat     381241
new_cat        3048872
dtype: int64

## Агрераційні операції над колонками

In [50]:
df.Age.mean(), df.Age.std()

(np.float64(38.822583565331705), 15.511611018090681)

In [51]:
df[['Age', 'Response']].mean()

Age         38.822584
Response     0.122563
dtype: float64

In [52]:
df[['Age', 'Response']].mode()

   Age  Response
0   24         0

In [55]:
df[['Age', 'Response']].agg(['mean', 'min', 'max']).round(3) # обчислює середнє, мін, макс для колонок Age і Response

         Age  Response
mean  38.823     0.123
min   20.000     0.000
max   85.000     1.000

In [56]:
df.drop(columns=['random_category'])

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response,New_col,new_cat,new_cat_dublicate,random_category_str,new_cat_cat
0,1,Male,44,1,28.0,0,> 2 Years,Yes,40454.0,26.0,217,1,0.3,Large,Large,3,Large
1,2,Male,76,1,3.0,0,1-2 Year,No,33536.0,26.0,183,0,0.3,Medium,Medium,2,Medium
2,3,Male,47,1,28.0,0,> 2 Years,Yes,38294.0,26.0,27,1,0.3,Small,Small,1,Small
3,4,Male,21,1,11.0,1,< 1 Year,No,28619.0,152.0,203,0,0.3,Small,Small,1,Small
4,5,Female,29,1,41.0,1,< 1 Year,No,27496.0,152.0,39,0,0.3,Large,Large,3,Large
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
381104,381105,Male,74,1,26.0,1,1-2 Year,No,30170.0,26.0,88,0,0.3,Medium,Medium,2,Medium
381105,381106,Male,30,1,37.0,1,< 1 Year,No,40016.0,152.0,131,0,0.3,Medium,Medium,2,Medium
381106,381107,Male,21,1,30.0,1,< 1 Year,No,35118.0,160.0,161,0,0.3,Medium,Medium,2,Medium
381107,381108,Female,68,1,14.0,0,> 2 Years,Yes,44617.0,124.0,74,0,0.3,Medium,Medium,2,Medium
381108,381109,Male,46,1,29.0,0,1-2 Year,No,41777.0,26.0,237,0,0.3,Large,Large,3,Large

In [57]:
new_df = df.drop(columns=['random_category']) #щоб точно видалило колонку, то потрібно записати в нову змінну

In [60]:
new_df.columns, df.columns

(Index(['id', 'Gender', 'Age', 'Driving_License', 'Region_Code',
        'Previously_Insured', 'Vehicle_Age', 'Vehicle_Damage', 'Annual_Premium',
        'Policy_Sales_Channel', 'Vintage', 'Response', 'New_col', 'new_cat',
        'new_cat_dublicate', 'random_category_str', 'new_cat_cat'],
       dtype='object'),
 Index(['id', 'Gender', 'Age', 'Driving_License', 'Region_Code',
        'Previously_Insured', 'Vehicle_Age', 'Vehicle_Damage', 'Annual_Premium',
        'Policy_Sales_Channel', 'Vintage', 'Response', 'New_col',
        'random_category', 'new_cat', 'new_cat_dublicate',
        'random_category_str', 'new_cat_cat'],
       dtype='object'))

In [62]:
 # інший спосіб видалення колонки random_category з датафрейма df
df.drop(columns= ['random_category'], inplance=True)

TypeError: DataFrame.drop() got an unexpected keyword argument 'inplance'. Did you mean 'inplace'?

In [63]:
df.drop('Annual_Premium').head()   # не спрацює, бо drop() за замовчуванням видаляє рядки (index), а не колонки

KeyError: "['Annual_Premium'] not found in axis"

In [64]:
df.drop(0).head() # видалило рядок з індексом 0

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response,New_col,random_category,new_cat,new_cat_dublicate,random_category_str,new_cat_cat
1,2,Male,76,1,3.0,0,1-2 Year,No,33536.0,26.0,183,0,0.3,2,Medium,Medium,2,Medium
2,3,Male,47,1,28.0,0,> 2 Years,Yes,38294.0,26.0,27,1,0.3,1,Small,Small,1,Small
3,4,Male,21,1,11.0,1,< 1 Year,No,28619.0,152.0,203,0,0.3,1,Small,Small,1,Small
4,5,Female,29,1,41.0,1,< 1 Year,No,27496.0,152.0,39,0,0.3,3,Large,Large,3,Large
5,6,Female,24,1,33.0,0,< 1 Year,Yes,2630.0,160.0,176,0,0.3,2,Medium,Medium,2,Medium

In [69]:
df.drop([0, 1, 4]).head()  # видалило рядки з індексом 0, 1, 4

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response,New_col,random_category,new_cat,new_cat_dublicate,random_category_str,new_cat_cat
2,3,Male,47,1,28.0,0,> 2 Years,Yes,38294.0,26.0,27,1,0.3,1,Small,Small,1,Small
3,4,Male,21,1,11.0,1,< 1 Year,No,28619.0,152.0,203,0,0.3,1,Small,Small,1,Small
5,6,Female,24,1,33.0,0,< 1 Year,Yes,2630.0,160.0,176,0,0.3,2,Medium,Medium,2,Medium
6,7,Male,23,1,11.0,0,< 1 Year,Yes,23367.0,152.0,249,0,0.3,2,Medium,Medium,2,Medium
7,8,Female,56,1,28.0,0,1-2 Year,Yes,32031.0,26.0,72,1,0.3,2,Medium,Medium,2,Medium

In [70]:
df.drop('Annual_Premium', axis=1).head()

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Policy_Sales_Channel,Vintage,Response,New_col,random_category,new_cat,new_cat_dublicate,random_category_str,new_cat_cat
0,1,Male,44,1,28.0,0,> 2 Years,Yes,26.0,217,1,0.3,3,Large,Large,3,Large
1,2,Male,76,1,3.0,0,1-2 Year,No,26.0,183,0,0.3,2,Medium,Medium,2,Medium
2,3,Male,47,1,28.0,0,> 2 Years,Yes,26.0,27,1,0.3,1,Small,Small,1,Small
3,4,Male,21,1,11.0,1,< 1 Year,No,152.0,203,0,0.3,1,Small,Small,1,Small
4,5,Female,29,1,41.0,1,< 1 Year,No,152.0,39,0,0.3,3,Large,Large,3,Large

In [71]:
def multicol_calculation(row):
    return row['Age']- row['Vintage']/365

In [72]:
df['complex_cal_col']= df.apply(multicol_calculation, axis =1)

In [73]:
df['complex_cal_col']

0         43.405479
1         75.498630
2         46.926027
3         20.443836
4         28.893151
            ...
381104    73.758904
381105    29.641096
381106    20.558904
381107    67.797260
381108    45.350685
Name: complex_cal_col, Length: 381109, dtype: float64

## Запис дата фрейма в файл

In [75]:
df.to_csv('res_lecture_3.csv')